spring.datasource.url: jdbc:mysql://localhost:3306/tasklib?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: 87654321
spring.jpa.hibernate.ddl: auto=none

someParameter:
  value: 5463